behaviors:
  PandaAgentBehavior:
    trainer_type: ppo        # must specify, even for recording
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    max_steps: 50000
    time_horizon: 64
    summary_freq: 1000
